config/routes.rb
Rails.application.routes.draw do
  get '/analytics', to: 'analytics#index'
  get '/articles/:id', to: 'articles#show'
  post 'articles/search', to: 'articles#search'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "articles#index"
end

app/models/analytic.rb
class Analytic < ApplicationRecord
  require 'fuzzystringmatch'
  validates :query, presence: true
  validates :query, length: { minimum: 3, maximum: 60 }
  validates :session_id, presence: true

  def searched?(search)
    jarow = FuzzyStringMatch::JaroWinkler.create(:native)
    similarity_percentage = jarow.getDistance(search, query)
    similarity_percentage > 0.8
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { minimum: 7, maximum: 60 }
  validates :body, presence: true, length: { minimum: 18, maximum: 300 }

  def self.title_search(query)
    where('title ilike :q', q: "%#{query}%").pluck(:title, :id).first(10) if exists?
  end
end

app/models/concerns/save_querry.rb
module SaveQuerry
  def self.save(query, session, articles)
    return if query.nil? || query.length < 3

    recent_querry = Analytic.new(query: query, articles: articles) # create a new analytic
    recent_querry.session_id = session # assign the session id to the analytic
    prev_querry = Analytic.where(session_id: session).last # get the last analytic of with the same session id
    if prev_querry.nil? || !prev_querry.searched?(query) # if the last analytic is not the same as the current one
      recent_querry.save # save the new analytic
    elsif prev_querry.query.length < query.length # if the current query is longer than the last one
      prev_querry.update(query: query, articles: articles) # update the last analytic
    end
  end
end

app/controllers/analytics_controller.rb
class AnalyticsController < ApplicationController
  def index
    @search_querries = Analytic.group(
      :query, :updated_at, :articles
    ).pluck('query, count(query) as COUNTER,articles, updated_at').sort_by do |a|
      a[1]
    end.reverse.first(10)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :check_session, only: [:search]

  def index
    @articles = []
  end

  def show
    @article = Article.find(params[:id])
  end

  def search
    if params[:query].empty?
      render(partial: '/shared/home', locals: { articles: [] })
    else
      articles = Article.title_search(params[:query])
      render(partial: '/shared/home', locals: { articles: articles })
  
      begin
        SaveQuerry.save(params[:query], session[:user_id], articles.length)
      rescue StandardError => e
        flash[:error] = "Error occurred while saving query: #{e.message}"
        # You can log the error for further investigation if needed
        Rails.logger.error("Error saving query: #{e.message}")
      end
    end
  end
  

  private

  def check_session
    session[:user_id] = SecureRandom.urlsafe_base64(16) if session[:user_id].nil?
  end
end

app/views/analytics/index.html.erb
<section class='analytics-section'>
  <h1 class='analytics-section__heading'> Analytics: popular searched articles </h1>
  <% if(@search_querries.length === 0)%>
    <p class='analytics-section__text'>No searches made yet</p>

    <%else%>

  <table class='table'>
  <tr class='table__row table__row--heading'>
    <th class='table__header'>Query</th>
    <th class='table__header'>number of searches</th>
    <th class='table__header'>articles</th>
  </tr>
  <% @search_querries.each_with_index do |querry, index| %>
<tr class='table__row'>  
  <td class='table__data'> <%= querry[0]  %> </td>
  <td class='table__data'> <%= querry[1] %> </td>
  <td class='table__data'><%= querry[2]  %> </td>
</tr>
  <% end %>
</table>
  <%end%>
</section>

app/views/articles/index.html.erb
<section class='headline-section'>
  <%= render partial: '/shared/home', locals: { articles: @articles } %>
  <span class="btn-container"><%= link_to 'Analytics', analytics_path, class: 'btn--link' %></span>
</section>

app/views/articles/show.html.erb
<section class="article">
    <div class="article__card">
        <h1 class="article__card--heading"><%= @article.title %> </h1>
        <p class="article__card--paragraph"> <%= @article.body  %> </p>
    </div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Search Engine | Realtime search engine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shared/_form.html.erb
<div class='form-container'>
  <%= form_with url: articles_search_path, method: :post, authenticity_token: false, data: { controller: "search", search_target: "form", turbo_frame: "articles" } do |form| %>
    <%= form.text_field :query,
      placeholder: "Search Articles...",
      autocomplete: "off",
      class: 'form-container__input',
      data: { action: "input->search#search" }
    %>
  <% end %>
</div>

app/views/shared/_home.html.erb
<div class='search'>
  <h1 class='search__heading'>Search Articles</h1>

  <%= render partial: '/shared/form' %>

  <%= turbo_frame_tag "articles" do %>
    <% if !articles.empty? %>
      <div class='queries'>
        <% articles.each do |article| %>
          <ul class="queries__list">
          <li class='queries__list--item'><a href='/articles/<%= article[1]%>' class='link'><%= article[0] %></a></li>
          </ul>
        <% end %>
      </div>
    <% end %>
  <% end %>
</div>